### ISSUE TITLE
hotkeys for slide type

### ISSUE THREAD

**Issue by yannpaul** [damianavila/RISE#114]
Does it make sense to have hot keys in command mode to change a cell's slide type. It would be useful in presentation mode, then you wouldn't need the cell toolbar (disabled currently). I propose that one sequence is used to cycle through the types, someting like Alt-s or Alt-t. And the cycling would not include 'skip', so you'd have to jump out of presentation mode or toggle the cell toolbar if that's what you'd like to do.

**Comment by damianavila** [comment]
This is interesting... there is some complexity from the UI perspective about how to select the difference cell types... having shortcuts can help people... but there is some problems because to actually see the changes you have to go out presentation more and enter again... in any case, having shorcuts at "design" time instead of going to the celltoolbar for each cell is interesting.

**Comment by Alexspayne** [comment]
This would be great to have.   Right now the only way to change the slide type is with the mouse, and that is the only thing I need to do with the mouse.  We are really close to being able to do with entirely with the keyboard.

**Comment by Alexspayne** [comment]
It probably makes sense to add this to Jupyter's core however since the metadata dropdown isn't exclusive to the RISE extension.

**Comment by damianavila** [comment]
#291 and #304 added default shortcuts for slide, subslide and fragments. In the future #306 the rest of the cell types will be available + configurable. Closing here since the main request is fulfilled with the current implementation.
