### ISSUE TITLE
Add a gh-pages branch

### ISSUE THREAD

**Issue by bollwyvl** [damianavila/RISE#126]
On #124, we discussed adding to the doc, and a place for the bookmarklet to be hosted that doesn't require on any more third parties than necessary. gh-pages will host everything over SSL on a CDN and can be safely ignored once automated, being built every time you push to master/merge a PR. Hooray!

I can't PR yet, since the branch doesn't exist, but here's a [proposed approach](https://github.com/bollwyvl/live_reveal/tree/rise-on-gh-pages), which has turned README into a notebook in RISE, then run through nbconvert for some delicious :dog: :pizza:. Looks [pretty good](http://bollwyvl.github.io/live_reveal)!

**Comment by adl** [comment]
I would suggest not to use reveal.js for the documentation of RISE (at least not without some explicit action from the user), because that makes the documentation harder to read/browse/search (compared to a single, regular web page) and that adds all sort of accessibility issues.

For instance here is what http://bollwyvl.github.io/live_reveal looks like on Firefox 39 for android.

The first page is simply blank:
![screenshot_2015-07-11-10-39-02](https://cloud.githubusercontent.com/assets/822900/8633104/f892a64c-27b9-11e5-8d85-230e611e093f.png)

and after sliding a couple of times until something appears you get this:
![screenshot_2015-07-11-10-41-28](https://cloud.githubusercontent.com/assets/822900/8633116/10e424aa-27ba-11e5-96d2-ae96c522920a.png)

**Comment by damianavila** [comment]
OK, the idea here is to have a sort of landing page, which right now is based on the README itself... but I think we have to split things:

* we need to have a nice landing page and having a reveal.js-based one makes a lot of sense.
* we need to actually have docs about how to use and customize this things... and that should be a simple HTML page which the landing one can reference...

And we have the best of the two worlds...

**Comment by damianavila** [comment]
@bollwyvl, I have created the gh-branch... so you can PR on it... and we can discuss which thing to keep on that and which ones port to a real doc...

**Comment by bollwyvl** [comment]
perhaps have a single documentation page (a la underscore, backbone), but
prominently feature a reveal show generated by RISE in an iframe, which can
be fullscreened? i agree with alexandre that a reveal show is not the best
first experience for someone who wants to *author* one.

better still, we'd hack an iframe to actually crack open a live demo on
tmpnb... but that is a no-go unless we got this hosted on a jupyter.org
domain... and the bookmarklet wouldn't work anyway.

in lieu of that, an animated GIF screencast would could help tremendously,
as i doubt many people will watch the whole youtube thing:
- start a notebook
- make some stuff, render it
- click the chart button
- see the slideshow
- navigate some slides
- double click and edit the stuff, render it
- exit the slideshow

also, apropos the mode switching, but out of scope for this issue: i was
hacking on a thing where in one mode I expanded the notebook container to
full-bleed (container-fluid) and hid the toolbar with some css
transitions... it magically just worked with RISE, too... perhaps a little
bit of transition magic would make switching modes less jarring.

**Comment by bollwyvl** [comment]
Re: screencast: those are hard to make! After finding byzanz, it took me about 100 tries to get this right, without typos, etc.

![](http://i.imgur.com/Pes3Uo3.gif)

I think it sums up the key things rise does in under 45 seconds :)

**Comment by damianavila** [comment]
>perhaps have a single documentation page (a la underscore, backbone), but
prominently feature a reveal show generated by RISE in an iframe, which can
be fullscreened? i agree with alexandre that a reveal show is not the best
first experience for someone who wants to *author* one.

Yep, sounds good...

> in lieu of that, an animated GIF screencast would could help tremendously,

Yep, completely agree... and you make a nice one!!

> also, apropos the mode switching, but out of scope for this issue: i was
hacking on a thing where in one mode I expanded the notebook container to
full-bleed (container-fluid) and hid the toolbar with some css
transitions... it magically just worked with RISE, too... perhaps a little
bit of transition magic would make switching modes less jarring.

Very interesting to see that... can you open another issue and show it? :wink:

**Comment by damianavila** [comment]
ping @bollwyvl, can you make the PR so we go ahead with this (I mean a slideshow with the RISElet).
I would like to have a very simple slideshow with ~3 slides and the RISElet in the last one.
We can use your branch as a starting point :wink:
Then (in another PR) we need a "real" docs page where we can include the gif and replace the README. It could be even a notebook since now it is rendered by github itself...

**Comment by damianavila** [comment]
Closing... since we already have docs here:https://damianavila.github.io/RISE/
