### ISSUE TITLE
Proposal: Make RISE part of jupyter?

### ISSUE THREAD

**Issue by ericmjl** [damianavila/RISE#168]
I'm not sure what you think about this, @damianavila, but would it make sense to make RISE distributed with Jupyter by default?

**Comment by bs1234** [comment]
+1

**Comment by damianavila** [comment]
From the Jupyter perspective, we (as a jupyter dev) have a high threshold to integrate something into the core... and we are splitting thing instead of integrating... what I have to do here is offer good ways to install RISE quickly w./ major issues... and I am actually working  on that (in some chucks of time).

**Comment by ericmjl** [comment]
Thank you for all of your efforts, Damian! Please let us know if there's
some way we can help :)

**Comment by icrtiou** [comment]
This is wonderful. I found this from Harvard's cs109 class. Thank you!
