### ISSUE TITLE
Using with mybinder.org?

### ISSUE THREAD

**Issue by r03ert0** [damianavila/RISE#235]
mybinder.org allows one to install jupyter notebook's requirements online, but only using pip install. Is there a way of using RISE together with binder?

**Comment by mjbright** [comment]
pip install is only one method.

In fact mybinder will first look for a Docker file, otherwise a pip
requirements.txt or finally a Conda yml file.

I included RISE in a presentation I did at EuroPython using this Dockerfile
<https://github.com/mjbright/jupyter-for-everything-else/blob/master/Dockerfile>,
I wanted to be able to run my presentation online in case something
happened to my PC ....

**Comment by r03ert0** [comment]
awesome! thanks!

**Comment by damianavila** [comment]
FYI, there is a pip package if you don't want to install from source... just check the readme activation step after installing with pip: https://github.com/damianavila/RISE#installation
