### ISSUE TITLE
full screen black background 

### ISSUE THREAD

**Issue by zahachtah** [damianavila/RISE#261]
I'm on a Mac and with both sfari and chrome when I press "f" when running jupyter notebook in RISE slideshow I both go into full screen and also start the find/replace of jupyter. But even when I close find/replace dialog the background of the slideshow is black, only the relevant text or image is white background. 

I guess the first is just a collision of keyshorts between rise and jupyter?

but the black background issue?

I'd much appreciate help in finding a solution to these issues.

**Comment by zahachtah** [comment]
Even when I load a slideshow through the slideviewer.herokuapp.com site and press "f" I don't get the find/replace but I do get a black background instead of a white one. Any ides?

**Comment by damianavila** [comment]
This is actually fixed in master with #256.
I should be able to release some beta version soon containing the fixes.

**Comment by damianavila** [comment]
Btw, the slideshow.heroku apps should not be used... it is a pretty old stuff guarantied to fail because it is un-maintained. Actually, the same functionality lives now in nbviewer.

**Comment by zahachtah** [comment]
Ok, thats sweet. Is there any simple way to install master? Or not recomended?

**Comment by damianavila** [comment]
Development instructions lieve here: https://github.com/damianavila/RISE#development
But I would suggest to wait a little bit if you are not in a hurry.

Btw... I am working now in a new brach to update RISE to the latest release. Regrettably, fullscreen mode from inside RISE will be disable because it mess bad with codemirror cells. The alternative will be just setup the browser fullscreen BEFORE starting RISE. In that way, Reveal.js performs the correct calculations and do not break the code cells. Just a mention for the future.

**Comment by damianavila** [comment]
> Btw... I am working now in a new brach to update RISE to the latest release. Regrettably, fullscreen mode from inside RISE will be disable because it mess bad with codemirror cells. The alternative will be just setup the browser fullscreen BEFORE starting RISE. In that way, Reveal.js performs the correct calculations and do not break the code cells. Just a mention for the future.

RISE is available now and you can not FullScreen from inside the slide. Closing here.

**Comment by zahachtah** [comment]
ok, thanks for awesome work, I use it all the time!

**Comment by damianavila** [comment]
> ok, thanks for awesome work, I use it all the time!

Thanks! And very happy to see people find it useful.
