### ISSUE TITLE
Generate a static version which can be served on the web

### ISSUE THREAD

**Issue by drorata** [damianavila/RISE#313]
How can I serve a finished deck on the web? For example on GitHub pages?

I tried to use `nbcovert` but it messed up the size of embedded images and I don't know how to serve the generated HTML.

**Comment by damianavila** [comment]
Yes, you should use `nbconvert` to convert your ipynb to the static slideshow.
If you push the HTML file to gh-pages, it should serve it.
You also need to be sure to ship `reveal.js` alonside with the ipynb, or alternative, point to the reveal.js CDN (default experience when converting to slides with `nbconvert`, IIRC).
You have one very old example here: https://github.com/damianavila/hackperiodismo/tree/gh-pages, it should give you an idea about how to do it. 
I will close this one because it is not a RISE issue, but you can keep commenting your experience.

Thanks!

**Comment by drorata** [comment]
I am failing to serve. I downloaded reveal.js and replaced `index.html` with the output of `nbconvert`, but it doesn't work and the resulting slides are not served properly.

**Comment by damianavila** [comment]
Can you share the repo so I can take a look? Thanks.

**Comment by drorata** [comment]
Here are the slides: https://github.com/rebuy-de/ds-ai-in-ds-best-practices
