### ISSUE TITLE
question about notes, and more generally about reveal plugins

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#352]
Hey there

PR #226 caught my attention because the feature to have the ability to freely draw is something I could use as well

Because the current code of #226 won't blend in the master branch for various reasons, I was trying to scaffold something along the same lines but based on my own #344, as that would give me an easy way to configure/activate the new feature

That's the point where I realized that:
1. the Notes business was also based on a reveal plugin 
1. and I had no idea how the Notes thingy was supposed to work anyway
1. so either I just don't know how to use it, or it's broken

I don't think I've read anything in the doc about how to use the Notes, can anyone shed some light on that ?

I'm asking also because the way I am trying to get reveal to load the chalkboard plugin is mimicked on what is in place for the notes plugin, and it'd help to know for sure if that works or not in my environment.

**Comment by damianavila** [comment]
> PR #226 caught my attention because the feature to have the ability to freely draw is something I could use as well

Yep, it is very interesting!

> the Notes business was also based on a reveal plugin

Yep

> and I had no idea how the Notes thingy was supposed to work anyway
> so either I just don't know how to use it, or it's broken

Notes are not working in RISE, there is an open issue about this here: https://github.com/damianavila/RISE/issues/174

I disabled the shortcut for the speaker notes because it was opening just the notebook view and not the slideshow view: https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L459-L465
We probably need to modify the notes plugin a little bit to be able to show the slideshow view.

**Comment by parmentelat** [comment]
thanks for the feedback, I'm closing this then
