### ISSUE TITLE
nbtutor button are not displayed

### ISSUE THREAD

**Issue by reberac** [damianavila/RISE#360]
Hi again,
Now I'm trying to use the extension nbtutor (https://github.com/lgpage/nbtutor) in slide mode, however the buttons on the right do not appear (it works well in notebook view).
Any idea..?
Thanks !
Aurélie

**Comment by parmentelat** [comment]
I've taken a very quick look 

First off, thanks for the pointer as I was not aware of nbtutor actually, and have been using for quite some time my own iframe-based solution to piggyback pythontutor; quite interesting

now to come back to your issue, what I could see is that `nbtutor` inserts its buttons outside of the output area, in a zone that usually contains the cell toolbar - and in this particular instance I found myself with the slide toolbar replaced with the nbtutor toolbar

but the point is, that area is not exposed to reveal in slideshow mode, so it's no wonder that the buttons are gone. I'm not quite sure if/how we can go about that in some sane way, and I agree it's a pity because showing tutor-based examples during a course is not an atypical use case

as a work around I can direct you to my iframe-based thing at <https://github.com/parmentelat/ipythontutor> which is less cool because less nicely integrated in the notebook, but more robust - especially on the spectrum of things that pythontutor can display nicely, as opposed to nbtutor that at first sight is more limited; but I might be wrong on that one... Plus, it will play more nicely with RISE ;)

**Comment by reberac** [comment]
Thank you so much for having suggested your iframe-based solution, it works perfectly !
It is not link to RISE but I have a question for you regarding pythontutor. 
I've tried a very simple code a = 3 and I do not understand why the object 3 is in the global frame and not in "objects"
<img width="594" alt="capture d ecran 2018-03-13 a 23 09 14" src="https://user-images.githubusercontent.com/16498537/37372616-997b3884-2713-11e8-9a59-b55336ab027f.png">

I miss something..?
Thank you

**Comment by parmentelat** [comment]
good to hear :)

IIRC pythontutor used to use a presentation more like you seem to expect; it's only my interpretation but I feel like they have evolved to this layout in order to optimize the space used, and to become able to illustrate more everyday code in a given amount of space. The point being that atomic values like ints and floats and the like being not mutable, displaying them one way or the other doesn't change the semantics of your program :)
There are ways to customize pythontutor's output, and ther might be a setting to show stuff as you expect it te be.
Again all this is just a guess from my part, and of course the author of pythontutor would be the person to talk to about that if that's an issue

**Comment by parmentelat** [comment]
oh and there's this FAQ where your question is answered
https://github.com/pgbovine/OnlinePythonTutor/blob/master/v3/docs/user-FAQ.md

**Comment by reberac** [comment]
Hi, thank you again !
I found the option heapPrimitives that has to be set to true on the magic line.
But I agree that nbtutor play more nicely in RISE ;-)

**Comment by samm-github** [comment]
Hello, 
Can you please help with this error 'UsageError: Line magic function `%%nbtutor` not found.'
I have tried a few options as below, but no luck


# ! jupyter nbextension install --overwrite --symlink --sys-prefix --py nbtutor
! jupyter nbextension enable --sys-prefix --py nbtutor
!jupyter nbextension enable nbtutor --py --sys-prefix
%reload_ext nbtutor

%%nbtutor -r -f

# %%ipythontutor
a= 1
a

**Comment by samm-github** [comment]
HI, 
can you please help this error message -UsageError: Line magic function `%%nbtutor` not found.
 i tried a few options as below, but no luck


# ! jupyter nbextension install --overwrite --symlink --sys-prefix --py nbtutor
 #! jupyter nbextension enable --sys-prefix --py nbtutor
 #!jupyter nbextension enable nbtutor --py --sys-prefix
%reload_ext nbtutor

%%nbtutor -r -f


a= 1
a

**Comment by parmentelat** [comment]
this question seems to rather belong 100% in the nbtutor project, no ?

**Comment by Naereen** [comment]
I think we can close this one, and focus on the more detailed #587.
