### ISSUE TITLE
Missing YAML file?

### ISSUE THREAD

**Issue by boffi** [damianavila/RISE#380]
Yesterday I (re)installed RISE and `jupyter_nbextensions_configurator` using `conda`
```
$ conda install -c conda-forge jupyter_nbextensions_configurator
$ conda install -c damianavila82 rise
```
While in the fine docs I can see [this image](http://rise.readthedocs.io/en/latest/_images/configurator.png) , in the configurator running on my computer all I can see is

> rise/main
This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though.

**Comment by parmentelat** [comment]
Hi

this nbconfigurator thing is a feature that is supposed to ship with 5.3.0 that is still in the works, and not officially out

I'm guessing the confusion is due to us having published the URL to the doc on readthedocs, which as of now is in sync with the unstable candidate for 5.3.0, while what you get with conda is still 5.2.0

Specifically:
  * http://rise.readthedocs.io/en/latest/ is about 5.3.0 (that will contain nbconfigurator)
  * http://rise.readthedocs.io/en/5.2.0/ is about the currently stable version
  
this being said, we plan on releasing 5.3.0 within the next couple of weeks hopefully (see #377)

**Comment by boffi** [comment]
I _suspected_ that the problem was not in the released RISE but rather in the docs being out of sync (that's why I used a question mark in the title).  OK, let's close this and wait for 5.3! Thank you very much for your answer and  all the good stuff.
