### ISSUE TITLE
404 issue on https://mybinder.org/v2/gh/parmentelat/RISE.git/doc2?filepath=examples%2FREADME.ipynb

### ISSUE THREAD

**Issue by jason-s** [damianavila/RISE#404]
I get a 404 not found on https://mybinder.org/v2/gh/parmentelat/RISE.git/doc2?filepath=examples%2FREADME.ipynb

**Comment by damianavila** [comment]
If you wait for a few seconds, the repo will load and you will have the RISE binder to play with... I need to figure it out why the preview is giving 404. It should be loading something like this: https://nbviewer.jupyter.org/format/slides/github/parmentelat/RISE/blob/doc2/examples/README.ipynb#/
That notebook is in a branch so that could be the issue. Additionally, binder probably is not aware of the RISE nature on that specific ipynb.

**Comment by rs2** [comment]
@damianavila By default BinderHub looks in `/notebooks` subfolder.

**Comment by parmentelat** [comment]
the original issue seems to have gone for me after I pushed commit 1621fe9799cb17cd1c6fc080f7a2281f189530db
(for now you need to start from the 'stable' version in readthedocs to see the change)

feel free to re-open this issue if needed
