### ISSUE TITLE
Tables are rendered too small

### ISSUE THREAD

**Issue by memeplex** [damianavila/RISE#483]
Here is the slide source code (Markdown):

```
## Análisis de convergencia

Sea $\rho = err_{est} + err_{opt}$, la siguiente tabla compara el numero de iteraciones y el tiempo total para conseguir un determinado $\rho$ en GD *vs.* SGD:

| Métrica               | Determinístico   | Estocástico |
|-----------------------|------------------|-------------|
| Tiempo por iteración  |                n |           1 |
| Número de iteraciones |    $log(1/\rho)$ |    $1/\rho$ |
| Tiempo total          | $n\,log(1/\rho)$ |    $1/\rho$ |

Podemos ver que el tiempo total para obtener una precisión $\rho$ es exponencialmente mayor en SGD pero, por otro lado, no depende del tamaño de la muestra $n$. 

Si nuestra muestra es muy grande, un optimizador con peor tasa de convergencia puede ser preferible si reduce rápidamente el error de estimación.
```

Here is the output of downloading as reveal.js slides:

![image](https://user-images.githubusercontent.com/2845433/60368393-1caaad80-99c7-11e9-9baa-9558d0687f12.png)

Here is the output of previewing using RISE:

![image](https://user-images.githubusercontent.com/2845433/60368438-406df380-99c7-11e9-8817-294427f16da3.png)

**Comment by parmentelat** [comment]
hi

with what version of rise is that ?

I did some improvement about that issue in the dev release, if you have a chance can you try that out ?

you can install that dev release with

` pip install -U --pre rise`

**Comment by memeplex** [comment]
Hi, thanks, it fixed the reported issue but broke many other things for worst:

1) Everything is too big and in many slides it gets clipped.

2) If I change height and width to, say, 80%, there is no improvement.

3) If I change height and width to, say, 800px, the slides become so big that I can only see the top left quarter of them.

**Comment by memeplex** [comment]
Another problem: I set width = 50%, the font is still huge but the slide is clipped so about a half is not visible. There is something really wrong with the scale.

**Comment by memeplex** [comment]
Well, some of the problems are present in the stable version too.

1. As before, width=<n>% set clipping, not scaling, behavior. This seems wrong to me.
2. As before, width=<n>px is broken, just a quarter or less of the slide is visible, the offset is huge.

I set my browser zoom level to 110% because jupyter notebooks look a bit small in my screen. I need to set width to less than 100% but AFAICS I'm unable to do that.

**Comment by parmentelat** [comment]
Hey there

I a little confused; your first message was pointing out the size of rendered markdown tables

this is a known issue, there is a solution with the stable release, that involves injecting your own settings through custom css style, as described in the documentation https://rise.readthedocs.io/en/stable/customize.html#adding-custom-css

I had been suggesting for you to use the dev release because it contains a fix for that specific table-size issue, but if that’s not workable for you it is probably better to rollback tto the stable release

—
as far as the other problems that you describe:

generally speaking it is not necessary to specify a width or height, and better practice to use the browser’s zoom feature to suit the current display settings (especially as it is notoriously hard to make any reliable assumption about the video-projector that you’ll end up using)

if you need to discuss this aspect further, I suggest that you open a separate issue

**Comment by memeplex** [comment]
> if you need to discuss this aspect further, I suggest that you open a separate issue

https://github.com/damianavila/RISE/issues/484

**Comment by parmentelat** [comment]
I'm closing this one, feel free to re-open if you're still struggling with the table size thing

FYI the CSS that we have in place in the dev release is this:
https://github.com/damianavila/RISE/commit/3d0e71c07f3fb83e1e0da7dfc0b67b7af1b8f36b
