### ISSUE TITLE
Slide / Subslide numbers not correctly displayed

### ISSUE THREAD

**Issue by cmencar** [damianavila/RISE#517]
When the slide number is greater than 9 and the subslide number is greater than 9, the marker on the bottom right is not correctly displayed because the numbers overlap with the arrows.
![image](https://user-images.githubusercontent.com/6205430/67038701-37dd2c80-f120-11e9-9893-63d65fe1bd82.png)

**Comment by parmentelat** [comment]
I suggest you give a try to the dev release - that is about to be published as the plain version for rise - with

`pip install -U --pre rise`

this version 5.6 comes with a more recent release of `reveal.js` and this problem is mostly solved with this release; here's what it looks like with one of my presentations

![image](https://user-images.githubusercontent.com/4519227/67050382-ab8b3380-f138-11e9-836a-fa734e07427b.png)

**Comment by damianavila** [comment]
@cmencar 

> this problem is mostly solved with this release

Releasing this weekend, so you should have a solution by the next week if you catch the new version.
