### ISSUE TITLE
overview of styling somewhere available?

### ISSUE THREAD

**Issue by nipuli** [damianavila/RISE#528]
Hi,

not really an issue, more a question.

I just switched from `nbconvert --to-slides` to _rise_ and appreciate it very much - so a big thanks at first!

I understand (a bit) the different ways to change layout, but I'm missing knowledge about the thousands of parameters. Is there an **overview of variables**, especially font sizes (markdown, code-input, code-output, latex and so on? Or a "**howto write your own theme**"? Many values have no effect, maybe due to overwrite by something else. And the config-tool has, of course, far less possibilities, none of the mentioned above. The e.g.  `jt -t grade3 -fs 13 -ofs 13 -nfs 13` did not what I hoped for.

Background: My usage is showing slides: mixed markdown, code (input highlighted together with output), images and latex formula.
So the first thing was trying themes in order to have the font sizes equally big, which isn't the default.
I now did this successfully, at least for some, by changing several values in the `~/.jupyter/custom/custom.css`. Mainly by try&error and the inspector tool of firefox. 
But in order to change the far too big size in the presenter window, I failed. Instead I had to change the value `.speaker-controls-notes .value { font-size: 1.2em; }` in the file 
`anaconda3/pkgs/rise-5.6.0-py37_0/share/jupyter/nbextensions/rise/notes_rise` which presumably will be changed with the next upgrade. I hope, there is a better method?

Thanks a lot!
Uli

**Comment by parmentelat** [comment]
Hi
For a bit of background, let me say that rise in itself is not about themes and layouts and similar; or at least, we try our best to mess with that on as small as possible a scale, i.e. when it cannot be avoided
The bulk of that is actually in the `reveal.js` scope, and I suggest you start there; the themes in particular natively come from reveal, even though we patch them slightly, only for the sake of supporting darker backgrounds
You are right that it can be confusing to write css for a rise document, reason being that we de facto inherit styling from both jupyter and reveal, so it sometimes requires to write very specific rules so that they actually trigger
So I guess the short answer is we do not have the kind of doc that you are looking for; most people, including me, take their inspiration from a dive in the html elements through their browser devel tools, although this can at times be frustrating of course

ps. I have no idea what you mean with `jt -t grade3 -fs 13 -ofs 13 -nfs 13 `

**Comment by nipuli** [comment]
Hi
thanks a lot for your answer, it is much appreciated and i understand more clearly now. I will have a look for reveal.js and jupyter itself, too. 

It's less a question of "frustrating", yes a little "confusing", but for sure time consuming... Especially now after the Pareto-principle applies ;-)

Besides: "jt" is the themes provided by `conda install -c conda-forge jupyterthemes`, "grade3" is one of them (best fitting my needs so far), the three options should deal with **f**ont-**s**izes.  

Have a good time!
Uli

**Comment by parmentelat** [comment]
> Besides: "jt" is the themes provided by conda install -c conda-forge jupyterthemes, "grade3" is one of them (best fitting my needs so far), the three options should deal with font-sizes.

thanks for making that clear, I have no exposure to any of these; as you have understood now, the only themes that ship with rise are the native themes that come with reveal.js  
some tweaking probably would not hurt, but as I said we try to be as independant as possible from reveal itself, and are operating essentially on a very limited time budget, so..

**Comment by kurtmckee** [comment]
It appears that this ticket can be closed.
