### ISSUE TITLE
CSS help to remove space above heading?

### ISSUE THREAD

**Issue by firasm** [damianavila/RISE#541]
I'm having some trouble formatting my Jupyter RISE slides because there is an unreasonable amount of whitespace above my headings.

I've tried inspecting them in my Safari Web inspector, but not sure what to do with that property. I have a custom css already so I know how to use that... 

I'd like to eliminate the orange bit and move the heading up.

![Screen Shot 2020-03-12 at 3 19 38 PM](https://user-images.githubusercontent.com/2507459/76571599-1d13a780-6475-11ea-94e2-ad120229e578.png)

Thanks in advance!

**Comment by parmentelat** [comment]
you're going to want to set e.g. `padding-top: 0px;` to the outlined element
your snapshot confuses me a little because the bottom pane has a `div#notebook` selected, but obviously the element that you want to set that property on is a `h4`

so it must be somewhere under `div#notebook`, and you'll need to dig into that a little more accurately to identify the CSS selector that you will attach the `padding-top: 0px;` property on

**Comment by firasm** [comment]
Ahh I think I led you astray with that screenshot! I don't think I clicked on the header. 

Here is the correct one, and you're right - it would be h4 in the example above, and is h1 below.
![Screen Shot 2020-03-12 at 8 06 44 PM](https://user-images.githubusercontent.com/2507459/76586105-1d279d80-649d-11ea-931e-76bad0c1c617.png)

Now to guess and test how to add this to the CSS to set padding-top: 0px. Thanks!

**Comment by firasm** [comment]
Aha! got it ... 

add this to the css file:

```
div.inner_cell>div.text_cell_render.rendered_html h1 {
    margin-top: 0px;
}
```

<img width="327" alt="Screen Shot 2020-03-12 at 8 16 40 PM" src="https://user-images.githubusercontent.com/2507459/76586712-eb173b00-649e-11ea-87ee-2820207e68f6.png">
