### ISSUE TITLE
 RISE not showing because install uses notebook version 7

### ISSUE THREAD

**Issue by wapiflapi** [damianavila/RISE#643]
I install RISE in a clean virtualenv and  I see the new notebook interface and things don't work as described in the documentation: 
- The button to start the slideshow doesn't show,
- There is no `View > Cell Toolbar`
- etc.

I was installing using `pip install RISE`.

The `setup.py` specifies 'notebook>=6.0', and when installing we endup with `notebook==7`:

```
$ python -m venv venv
(venv) $ pip install RISE
[...]
(venv) $ pip freeze | grep notebook
notebook==7.0.2
notebook_shim==0.2.3

```

I spent a long time figuring this out but it turns out I simply needed to:

```
$ python -m venv venv
(venv) $ pip install notebook==^6.0
(venv) $ pip install RISE
(venv) $ python -m noteboook
```

and everything works :smile: 

I suggest either changing the `setup.py` or adding this to the documentation.

... or maybe there is an unrelated bug and I missed something ?

**Comment by parmentelat** [comment]
Yes indeed, since July 19th, a fresh install of `pip install notebook` will bring nb7, which breaks every extension compatibility with notebook 6 - as advertised for several months already

for people interested in using RISE in jupyterlab and/or notebook-7, there is a successor:
`pip install jupyterlab-rise`
which is the outcome of
https://github.com/jupyterlab-contrib/rise

so yes this probably means that, as far as this RISE repo is concerned:
- the documentation should outline that it is mostly outdated
- the dependencies should be updated to explicitly pin `notebook < 7.0`

not sure how @damianavila feels about all this though

**Comment by wapiflapi** [comment]
For what it's worth, I had some issues getting rise lab to work. (it worked
but when editing code the result didn't update in the presentation, and
bugs like that.)

Probably off-topic here, but just so you know the context : I needed the
tried and tested robust version 😂

**Comment by luraess** [comment]
From the Julia side, it seems that indeed a workaround is to pin notebook < v7.0 as in https://github.com/JuliaPy/Conda.jl/issues/247#issuecomment-1713713961

Is there a way one could fix the issue and make it work with latest env?

**Comment by parmentelat** [comment]
@wapiflapi 

> For what it's worth, I had some issues getting rise lab to work. (it worked
but when editing code the result didn't update in the presentation, and
bugs like that.)

obviously this belongs in the jupyterlab-rise repo ;)

**Comment by parmentelat** [comment]
to address the initial post, I have updated the documentation in order to make it - hopefully - much clearer that
* rise works with nb classic only (notebook up to 6.x)
* rise is consequently  no longer actively maintained
* jupyterlab-rise is available and should be used with the recent jlab4/nb7 stack
